version: "3.7"

services:

  node:
    container_name: node
    image: supertypo/rusty-kaspad:latest
    restart: unless-stopped
    ports:
      - "16110:16110/tcp"
      - "16111:16111/tcp"
    volumes:
      - kaspad:/app/data/

volumes:
  kaspad:
